tsocks-1.8beta5

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2075,16 +2075,35 @@ EOF
   fi
 
   echo "$ac_t""$LIBCONNECT" 1>&6
+
+    echo $ac_n "checking "location of libc.so"""... $ac_c" 1>&6
+echo "configure:2081: checking "location of libc.so"" >&5
+  LIBC=
+  for DIR in '/lib' '/usr/lib'; do
+    if test "${LIBC}" = ""; then
+      LIBC=`$FIND $DIR -name "libc.so.?" 2>/dev/null | $TAIL -1`
+    fi
+  done
+
+  cat >> confdefs.h <<EOF
+#define LIBC "${LIBC}"
+EOF
+
+  if test "${LIBC}" = ""; then
+     { echo "configure: error: "not found!"" 1>&2; exit 1; }
+  fi
+
+  echo "$ac_t""$LIBC" 1>&6
 fi
 
 echo $ac_n "checking for correct select prototype""... $ac_c" 1>&6
-echo "configure:2082: checking for correct select prototype" >&5
+echo "configure:2101: checking for correct select prototype" >&5
 PROTO=
 for testproto in 'int n, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, struct timeval *timeout' 
 do
   if test "${PROTO}" = ""; then
     cat > conftest.$ac_ext <<EOF
-#line 2088 "configure"
+#line 2107 "configure"
 #include "confdefs.h"
 
       #include <sys/time.h>
@@ -2096,7 +2115,7 @@ int main() {
 
 ; return 0; }
 EOF
-if { (eval echo configure:2100: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:2119: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   PROTO="$testproto";
 else
@@ -2116,7 +2135,7 @@ EOF
 
 
 echo $ac_n "checking for correct connect prototype""... $ac_c" 1>&6
-echo "configure:2120: checking for correct connect prototype" >&5
+echo "configure:2139: checking for correct connect prototype" >&5
 PROTO=
 PROTO1='int __fd, const struct sockaddr * __addr, int len'
 PROTO2='int __fd, const struct sockaddr_in * __addr, socklen_t __len'
@@ -2129,7 +2148,7 @@ for testproto in "${PROTO1}" \
 do
   if test "${PROTO}" = ""; then
     cat > conftest.$ac_ext <<EOF
-#line 2133 "configure"
+#line 2152 "configure"
 #include "confdefs.h"
 
       #include <sys/socket.h>
@@ -2139,7 +2158,7 @@ int main() {
 
 ; return 0; }
 EOF
-if { (eval echo configure:2143: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:2162: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   PROTO="$testproto";
 else
@@ -2169,14 +2188,51 @@ cat >> confdefs.h <<EOF
 EOF
 
 
+echo $ac_n "checking for correct close prototype""... $ac_c" 1>&6
+echo "configure:2193: checking for correct close prototype" >&5
+PROTO=
+PROTO1='int fd'
+for testproto in "${PROTO1}" 
+do
+  if test "${PROTO}" = ""; then
+    cat > conftest.$ac_ext <<EOF
+#line 2200 "configure"
+#include "confdefs.h"
+
+      #include <stdlib.h>
+      int close($testproto);
+    
+int main() {
+
+; return 0; }
+EOF
+if { (eval echo configure:2210: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+  rm -rf conftest*
+  PROTO="$testproto";
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+fi
+rm -f conftest*
+  fi
+done
+if test "${PROTO}" = ""; then
+  { echo "configure: error: "no match found!"" 1>&2; exit 1; }
+fi
+echo "$ac_t""close(${PROTO})" 1>&6
+cat >> confdefs.h <<EOF
+#define CLOSE_SIGNATURE ${PROTO}
+EOF
+
+
 echo $ac_n "checking for correct poll prototype""... $ac_c" 1>&6
-echo "configure:2174: checking for correct poll prototype" >&5
+echo "configure:2230: checking for correct poll prototype" >&5
 PROTO=
 for testproto in 'struct pollfd *ufds, unsigned long nfds, int timeout' 
 do
   if test "${PROTO}" = ""; then
     cat > conftest.$ac_ext <<EOF
-#line 2180 "configure"
+#line 2236 "configure"
 #include "confdefs.h"
 
       #include <sys/poll.h>
@@ -2186,7 +2242,7 @@ int main() {
 
 ; return 0; }
 EOF
-if { (eval echo configure:2190: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:2246: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   PROTO="$testproto";
 else
